### ISSUE TITLE
remove rgmanager code TODO list

### ISSUE THREAD

**Issue by OndrejHome** [OndrejHome/ansible.ha-cluster-lvm#5]
To simplify the code the rgmanager-only version of this roles was created in https://github.com/OndrejHome/ansible.ha-cluster-lvm-rgmanager

Idea is to remove rgmanager code from this repository and keep only pacemaker related code.

TODO:
- [x] remove all rgmanager related code
- [x] re-test on EL6 pacemaker platform (at least CentOS 6.10 and RHEL 6.10) to confirm that this works for both tagging and clvm there
- [x] implement repository detection (from ondrejhome.ha-cluster.pacemaker code)
- [x] update documentation on examples and provide link to rgmanager role
